---
layout: single
title: "Javascript : 개념메모5 (Callbacks, Promise(+fetch), Async Await)"
author_profile: false
toc: true
toc_sticky: true
published: true
---

<br>

# 구조 정리 : 이벤트 루프

* Browser는 Javascript 엔진 말고도 Web API, Callback Queue, Event Loop가 있다.

* 비동기 작업에 해당하는 작업은 Web API에서 처리된다.

* 비동기 작업이 완료되면 다시 Callback Queue로 함수가 들어온다.

* Callback Queue에는 Web API의 콜백 함수들이 대기하게 된다.

* Event Loop는 Call Stack과 Callback Queue를 주시하다가 Call Stack이 비게 되면 먼저 들어온 순서대로 Callback Queue에 있는 함수들을 Call Stack에 넣어준다.

<hr>
<br>

# Callbacks, Promise(+fetch), Async Await

<div class="notice--info">
비동기 요청이 다수 존재하고 어느 하나의 요청이 다른 요청의 결과에 의존할 때는 어떻게 해야할까?
</div>

- [ ] 이전 해결방법
  Callback 함수로 비동기 작업을 해결했다.
  
- [ ] es6 도입 이후
  Promise로 비동기 작업을 해결했다.
  
- [ ] es7 도입 이후
  Async/Await으로 비동기 작업을 해결한다.

<br>

## Callbacks 함수

* 콜백 함수는 특정 함수에 매개변수로 전달된 함수이다. 그 콜백 함수는 함수를 전달받은 함수 안에서 호출된다. 그러나 가독성이 떨어지고 에러처리 시 복잡하다는 단점이 있다.

<br>

## Promise

* Promise 객체는 new 키워드와 생성자를 사용하여 만든다. 생성자는 매개변수로 '실행 함수'를 받는다. 이 함수는 매개 변수로 두 가지 함수를 받아야 한다. 첫 번째 함수(resolve)는 비동기 작업을 성공적으로 완료해 결과를 값으로 반환할 때 호출해야 한다. 두번째 함수는 작업이 실패하여 오류의 원인을 반환할 때 호출하면 된다. 두 번째 함수는 주로 오류 객체를 받는다.

* javascript 비동기 처리에 사용되는 객체이며 비동기 작업이 맞이할 미래의 완료 또는 실패와 그 결과 값을 나타낸다.

```javascript
function promiseExam() {
    return new Promise((resolve, reject) => {
    //즉, 작업 성공 후 받은 response를 resolve 함수의 매개인자로 넣어줌.
    //작업 실패 후 받은 response는 reject 함수의 매개인자로 넣어줌.
    const success = true;
    if (success) {
      resolve('성공!');
    } else {
      reject('실패!');
    }
  });
}

//.then으로 연결
promiseExam()
  .then((result) => {
    console.log("성공! : " + result);
  })
  .then((error) => { //.catch로 에러를 받아주어도 된다.
    console.log("실패 : " + error);
  })
  .finally(() => {
    console.log("작업종료..!");
  })
```

### Promise.all() , Promise.race()

* Promise.all()
  - 순회 가능한 객체에 주어진 모든 프로미스가 이행한 후, 혹은 프로미스가 주어지지 않았을 때 이행하는 Promise를 반환한다. 주어진 프로미스 중 하나가 거부하는 경우, 첫번째로 거절한 프로미스의 이유를 사용해 자신도 거부한다.

```javascript
const promise1 = Promise.reject('실패!');
const promise2 = 42;
const promise3 = new Promise((resolve, reject) => {
  setTimeout(resolve, 100, 'foo');
});

Promise.all([promise1, promise2, promise3]).then((values) => {
  console.log(values);
})
.catch((error) => {
  console.log("error : " + error);
})
//결과 : "error : 실패!"
```

<br>

* Promise.race()
  - iterable 안에 있는 프로미스 중에 가장 먼저 완료된 것의 결과값으로 그대로 이행하거나 거부한다.

```javascript
const promise1 = new Promise((resolve, reject) => {
  setTimeout(resolve, 500, 'one');
});

const promise2 = new Promise((resolve, reject) => {
  setTimeout(resolve, 100, 'two');
});

Promise.race([promise1, promise2]).then((value) => {
  console.log(value);
});
//결과 : "two"
```

## fetch

* fetcch() 내장 배열 메서드를 사용하여 promise를 지원하기 때문에 바로 이를 사용해도 좋다.
  - 값을 잘 가져오기 위해 JSON 객체로 변환을 해주어야 한다.

```javascript
fetch("http://www.naver.com")
  .then(response1 => {response1.json()})
  .then(json1 => console.log(json1))
  .then(() => fetch("http://www.naver.com"))
  .then(response2 => {response2.json()})
  .then(json2 => {console.log(json2)})
  .catch(error => {console.error(error)})
  .finally(() => {console.log('작업종료...!')})
```

<br>

## Async Await

<div class="notice--primary">
Async와 Await을 이용하여 더 깔끔하게 코드 작성<br>
await 뒤 작성한 코드가 완료될 때까지 기다리는 의미
</div>

<div class="notice--primary">
비동기 코드를 마치 동기 코드처럼 보이게 하며 가독성이 더 좋다. <br>
await는 async 내부 함수에서만 사용할 수 있고 try...catch 구문을 이용가능하다.
</div>

* 예시

```javascript
async function makeRequests() {
  try {
    const response1 = await fetch('https://www.naver.com');
    const jsonResponse1 = await(response1.json());
    console.log('jsonResponse1', jsonResponse1);

    const response2 = await fetch('https://www.naver.com');
    const jsonResponse2 = await(response2.json());
    console.log('jsonResponse2', jsonResponse2);
  } catch (error) {
    console.log(error)
  } finally {
    console.log("---작업 종료!---")
  }
}
```